# Generated by Django 4.2.13 on 2024-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dishes_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='categoryType',
            field=models.CharField(choices=[('Салаты', 'Салаты'), ('Супы', 'Супы'), ('Рецепты вторых блюд', 'Рецепты вторых блюд'), ('Дессерты', 'Дессерты'), ('Закуски', 'Закуски')], max_length=20, verbose_name='Категория'),
        ),
    ]
